version: "2.1"

networks:
  pm-net:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.1.0/24
volumes:
     mariadb-data:
     docker-data:
     processmaker-data:

services:
   mariadb:
    image: mariadb
    ports:
      - 3306:3306/tcp
    environment:
      MYSQL_ROOT_PASSWORD: "pmserver"
      MYSQL_DATABASE: "wf_workflow"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "pmserver"
    networks:
      - pm-net
    volumes:
      - mariadb-data:/var/lib/mysql
      - mariadb-logs:/var/lib/mysql
      - mariadb-conf:/var/lib/mysql
   
   redis:
    image: redis:6
    ports:
      - '6379:6379'
    networks:
      - pm-net
             
   remotedocker:
    image: docker:20-dind
    privileged: true
    ports:
      - '45003:45003'
    networks:
      - pm-net
    volumes:
      - ./certs:/certs
      - docker-data:/var/lib/docker
    environment:
      DOCKER_TLS_CERTDIR: '/certs'
      
   processmaker:
     image: eltercera/docker-processmaker
     ports:
       - "45001:443"
     depends_on:
      - mariadb
      - redis
      - remotedocker
     networks:
      - pm-net
     volumes:
      - ./certs:/certs/
      - ./.env:/opt/processmaker/.env
      - processmaker-data:/opt/processmaker/storage
     environment:
       WAIT_FOR_DEPENDENTS: 1
       DOCKER_HOST: 'tcp://remotedocker:45003'
       DOCKER_CERT_PATH: '/certs/client'
       DOCKER_TLS_VERIFY: 1
       NO_PROXY: '127.0.0.1,localhost,remotedocker:45003'
     
