version: "2.1"

services:
   mysql:
     image: mysql:5.6
     ports:
       - "45002:3306/tcp"

     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: PM-DBPassw0rd
       #MYSQL_USER: root
       #MYSQL_DATABASE: PM-DB
       #MYSQL_PASSWORD: PM-DBPassw0rd
     networks:
     - pm-net

   processmaker:
     depends_on:
     - mysql
     image: eltercera/docker-processmaker
     ports:
#       - "80:80"
       - "8091:80"
       - "8092:8080"
     restart: always
     environment:
       URL: "127.0.0.1"
     networks:
      - pm-net
networks:
  pm-net:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.1.0/24
